name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    #services:
    #  mssql:
    #    image: mcr.microsoft.com/mssql/server:2022-latest
    #    env:
    #      SA_PASSWORD: MyTestPassword
    #      ACCEPT_EULA: 'Y'
    #    ports:
    #      - 1433:1433

    strategy:
      matrix:
        version: [3.1.x, 6.0.x, 7.0.x, 8.0.x]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
